from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import get_db
from app.schemas.simulation import (
    SimulationRunRequest,
    SimulationRunResponse,
    SimulationStatusResponse,
    SimulationCleanupResponse
)
from app.simulation.config import SimulationConfig
from app.simulation.engine import TrafficSimulator
from app.simulation.cleanup import cleanup_simulation_data

router = APIRouter()


@router.post("/run", response_model=SimulationRunResponse, summary="Trigger a synthetic traffic simulation run")
async def run_simulation(
    req: SimulationRunRequest,
    db: AsyncSession = Depends(get_db)
):
    """
    Executes a controlled synthetic traffic simulation across the directed camera network.
    Generates synthetic vehicles, plates, and normalized detection observations.
    All records are marked with simulation metadata.
    """
    try:
        config = SimulationConfig(
            vehicle_count=req.vehicle_count,
            events_per_vehicle=req.events_per_vehicle,
            seed=req.seed,
            start_time=req.start_time
        )
        simulator = TrafficSimulator(config)
        result = await simulator.run(db_session=db)

        return SimulationRunResponse(**result)
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Simulation failed: {str(exc)}"
        )


@router.get("/status", response_model=SimulationStatusResponse, summary="Get simulation telemetry status")
async def get_simulation_status(
    db: AsyncSession = Depends(get_db)
):
    """
    Returns current counts of simulated vehicles, plates, and detection observations in the database.
    """
    veh_res = await db.execute(
        text("SELECT COUNT(*) FROM vehicles WHERE visual_features->>'simulation' = 'true' OR vehicle_uid LIKE 'veh_sim_%';")
    )
    total_veh = veh_res.scalar() or 0

    det_res = await db.execute(
        text("SELECT COUNT(*) FROM detections WHERE snapshot_path LIKE 'simulated://%' OR processing_metadata->>'simulation' = 'true';")
    )
    total_det = det_res.scalar() or 0

    plate_res = await db.execute(
        text("SELECT COUNT(*) FROM vehicle_plates WHERE anomaly_flags->>'simulation' = 'true';")
    )
    total_plates = plate_res.scalar() or 0

    last_time_res = await db.execute(
        text("SELECT MAX(timestamp) FROM detections WHERE snapshot_path LIKE 'simulated://%';")
    )
    last_time = last_time_res.scalar()

    return SimulationStatusResponse(
        is_running=False,
        total_simulated_vehicles=total_veh,
        total_simulated_events=total_det,
        total_simulated_plates=total_plates,
        last_simulation_time=last_time
    )


@router.post("/cleanup", response_model=SimulationCleanupResponse, summary="Purge all simulated records")
async def cleanup_simulation():
    """
    Safely deletes all synthetic records generated by the simulator.
    Does not affect cameras, road edges, or non-simulation entities.
    """
    result = await cleanup_simulation_data()
    return SimulationCleanupResponse(
        status="cleaned",
        detections_deleted=result["detections_deleted"],
        plates_deleted=result["plates_deleted"],
        vehicles_deleted=result["vehicles_deleted"],
        message=f"Cleaned {result['detections_deleted']} detections, {result['plates_deleted']} plates, and {result['vehicles_deleted']} vehicles."
    )
