"""create_initial_core_schema

Revision ID: e837934788a3
Revises: 
Create Date: 2026-08-27 10:46:11.577017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'e837934788a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('direction_angle', sa.Float(), nullable=True),
    sa.Column('road_name', sa.String(length=128), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('installation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_camera_id'), 'cameras', ['camera_id'], unique=True)
    op.create_index(op.f('ix_cameras_road_name'), 'cameras', ['road_name'], unique=False)
    op.create_index(op.f('ix_cameras_sector'), 'cameras', ['sector'], unique=False)
    op.create_index(op.f('ix_cameras_status'), 'cameras', ['status'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_uid', sa.String(length=64), nullable=False),
    sa.Column('vehicle_type', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('make', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('window_tint', sa.String(length=32), nullable=True),
    sa.Column('visual_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_color'), 'vehicles', ['color'], unique=False)
    op.create_index(op.f('ix_vehicles_first_seen_at'), 'vehicles', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_vehicles_last_seen_at'), 'vehicles', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_vehicles_vehicle_type'), 'vehicles', ['vehicle_type'], unique=False)
    op.create_index(op.f('ix_vehicles_vehicle_uid'), 'vehicles', ['vehicle_uid'], unique=True)
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plate_number', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('vehicle_description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_category'), 'watchlist', ['category'], unique=False)
    op.create_index(op.f('ix_watchlist_is_active'), 'watchlist', ['is_active'], unique=False)
    op.create_index(op.f('ix_watchlist_plate_number'), 'watchlist', ['plate_number'], unique=False)
    op.create_index(op.f('ix_watchlist_priority'), 'watchlist', ['priority'], unique=False)
    op.create_table('road_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_camera_id', sa.Integer(), nullable=False),
    sa.Column('destination_camera_id', sa.Integer(), nullable=False),
    sa.Column('distance_meters', sa.Float(), nullable=False),
    sa.Column('expected_min_travel_seconds', sa.Float(), nullable=False),
    sa.Column('expected_max_travel_seconds', sa.Float(), nullable=True),
    sa.Column('speed_limit_kmh', sa.Float(), nullable=True),
    sa.Column('road_name', sa.String(length=128), nullable=True),
    sa.Column('direction', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('source_camera_id != destination_camera_id', name='check_no_self_loop_edge'),
    sa.ForeignKeyConstraint(['destination_camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_camera_id', 'destination_camera_id', name='uq_source_destination_edge')
    )
    op.create_index(op.f('ix_road_edges_destination_camera_id'), 'road_edges', ['destination_camera_id'], unique=False)
    op.create_index(op.f('ix_road_edges_source_camera_id'), 'road_edges', ['source_camera_id'], unique=False)
    op.create_index('ix_road_edges_source_dest', 'road_edges', ['source_camera_id', 'destination_camera_id'], unique=False)
    op.create_table('trajectories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trajectory_uid', sa.String(length=64), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('plate_number', sa.String(length=32), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_camera_id', sa.Integer(), nullable=True),
    sa.Column('end_camera_id', sa.Integer(), nullable=True),
    sa.Column('total_distance_meters', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['end_camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['start_camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trajectories_end_time'), 'trajectories', ['end_time'], unique=False)
    op.create_index(op.f('ix_trajectories_plate_number'), 'trajectories', ['plate_number'], unique=False)
    op.create_index(op.f('ix_trajectories_start_time'), 'trajectories', ['start_time'], unique=False)
    op.create_index(op.f('ix_trajectories_status'), 'trajectories', ['status'], unique=False)
    op.create_index(op.f('ix_trajectories_trajectory_uid'), 'trajectories', ['trajectory_uid'], unique=True)
    op.create_index(op.f('ix_trajectories_vehicle_id'), 'trajectories', ['vehicle_id'], unique=False)
    op.create_table('vehicle_plates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('normalized_plate', sa.String(length=32), nullable=False),
    sa.Column('raw_plate_text', sa.String(length=64), nullable=True),
    sa.Column('state_code', sa.String(length=8), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('anomaly_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_plates_normalized_plate'), 'vehicle_plates', ['normalized_plate'], unique=False)
    op.create_index(op.f('ix_vehicle_plates_state_code'), 'vehicle_plates', ['state_code'], unique=False)
    op.create_index(op.f('ix_vehicle_plates_status'), 'vehicle_plates', ['status'], unique=False)
    op.create_index(op.f('ix_vehicle_plates_vehicle_id'), 'vehicle_plates', ['vehicle_id'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('detection_uid', sa.String(length=64), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('plate_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plate_number', sa.String(length=32), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('vehicle_color', sa.String(length=64), nullable=True),
    sa.Column('vehicle_type', sa.String(length=64), nullable=True),
    sa.Column('snapshot_path', sa.String(length=255), nullable=True),
    sa.Column('direction_travel', sa.String(length=64), nullable=True),
    sa.Column('plate_anomaly_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('association_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plate_id'], ['vehicle_plates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_camera_id'), 'detections', ['camera_id'], unique=False)
    op.create_index('ix_detections_camera_timestamp', 'detections', ['camera_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_detections_detection_uid'), 'detections', ['detection_uid'], unique=True)
    op.create_index(op.f('ix_detections_plate_id'), 'detections', ['plate_id'], unique=False)
    op.create_index(op.f('ix_detections_plate_number'), 'detections', ['plate_number'], unique=False)
    op.create_index('ix_detections_plate_timestamp', 'detections', ['plate_number', 'timestamp'], unique=False)
    op.create_index(op.f('ix_detections_timestamp'), 'detections', ['timestamp'], unique=False)
    op.create_index(op.f('ix_detections_vehicle_id'), 'detections', ['vehicle_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('plate_number', sa.String(length=32), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('detection_id', sa.BigInteger(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('evidence_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_camera_id'), 'alerts', ['camera_id'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_detection_id'), 'alerts', ['detection_id'], unique=False)
    op.create_index(op.f('ix_alerts_plate_number'), 'alerts', ['plate_number'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_vehicle_id'), 'alerts', ['vehicle_id'], unique=False)
    op.create_table('trajectory_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trajectory_id', sa.Integer(), nullable=False),
    sa.Column('detection_id', sa.BigInteger(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=64), nullable=True),
    sa.Column('transition_time_seconds', sa.Float(), nullable=True),
    sa.Column('transition_distance_meters', sa.Float(), nullable=True),
    sa.Column('speed_estimate_kmh', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trajectory_id'], ['trajectories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trajectory_id', 'sequence_order', name='uq_trajectory_sequence_order')
    )
    op.create_index(op.f('ix_trajectory_events_timestamp'), 'trajectory_events', ['timestamp'], unique=False)
    op.create_index('ix_trajectory_events_traj_seq', 'trajectory_events', ['trajectory_id', 'sequence_order'], unique=False)
    op.create_index(op.f('ix_trajectory_events_trajectory_id'), 'trajectory_events', ['trajectory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trajectory_events_trajectory_id'), table_name='trajectory_events')
    op.drop_index('ix_trajectory_events_traj_seq', table_name='trajectory_events')
    op.drop_index(op.f('ix_trajectory_events_timestamp'), table_name='trajectory_events')
    op.drop_table('trajectory_events')
    op.drop_index(op.f('ix_alerts_vehicle_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_plate_number'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_detection_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_camera_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_detections_vehicle_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_timestamp'), table_name='detections')
    op.drop_index('ix_detections_plate_timestamp', table_name='detections')
    op.drop_index(op.f('ix_detections_plate_number'), table_name='detections')
    op.drop_index(op.f('ix_detections_plate_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_detection_uid'), table_name='detections')
    op.drop_index('ix_detections_camera_timestamp', table_name='detections')
    op.drop_index(op.f('ix_detections_camera_id'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_vehicle_plates_vehicle_id'), table_name='vehicle_plates')
    op.drop_index(op.f('ix_vehicle_plates_status'), table_name='vehicle_plates')
    op.drop_index(op.f('ix_vehicle_plates_state_code'), table_name='vehicle_plates')
    op.drop_index(op.f('ix_vehicle_plates_normalized_plate'), table_name='vehicle_plates')
    op.drop_table('vehicle_plates')
    op.drop_index(op.f('ix_trajectories_vehicle_id'), table_name='trajectories')
    op.drop_index(op.f('ix_trajectories_trajectory_uid'), table_name='trajectories')
    op.drop_index(op.f('ix_trajectories_status'), table_name='trajectories')
    op.drop_index(op.f('ix_trajectories_start_time'), table_name='trajectories')
    op.drop_index(op.f('ix_trajectories_plate_number'), table_name='trajectories')
    op.drop_index(op.f('ix_trajectories_end_time'), table_name='trajectories')
    op.drop_table('trajectories')
    op.drop_index('ix_road_edges_source_dest', table_name='road_edges')
    op.drop_index(op.f('ix_road_edges_source_camera_id'), table_name='road_edges')
    op.drop_index(op.f('ix_road_edges_destination_camera_id'), table_name='road_edges')
    op.drop_table('road_edges')
    op.drop_index(op.f('ix_watchlist_priority'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_plate_number'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_is_active'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_category'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_vehicles_vehicle_uid'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_vehicle_type'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_last_seen_at'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_first_seen_at'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_color'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_cameras_status'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_sector'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_road_name'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_camera_id'), table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###
